name: Java CD

on:
  push:
    branches: [ "main", "feat/cd" ]

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest

      steps:

        - name: Build application
          run:
            mvn clean
            mvn -B package --file pom.xml

        - name: Build Docker Image
          uses: docker/build-push-action@v2
          with:
            context: .
            dockerfile: Dockerfile
            push: false
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/health-checker-app:latest

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Push to Docker Hub
          uses: docker/build-push-action@v2
          with:
            context: .
            dockerfile: Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/health-checker-app:latest



      
        
        
    



